image: golang:bullseye

format:
  stage: build
  script:
    - go fmt ./...

compile:
  stage: build
  script:
    - make out/7hlc
  artifacts:
    paths:
      - out

vet:
  stage: test
  script:
    - go vet ./...

test:
  stage: test
  script:
    - go test -race ./...
