image: golang:bullseye

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...
    - go test -race ./...

compile:
  stage: build
  script:
    - make out/7hlc
  artifacts:
    paths:
      - out
